### PR TITLE
offset childrens' GridCells from their parent

### LINKED ISSUE #11: Childrens' `GridCell` is ignored
When children of entities have their own `GridCell`, that `GridCell` is ignored entirely (and silently). I think the behaviour should be that the children's `GridCell` is used as a relative offset to the parent.

Alternatively the traversal should emit a warning about the ignored `GridCell`.

What do you think should happen here? I'd be happy to provide the impl

### PR DESCRIPTION
**Pull request by oli-obk**
Modulo some cleanups and writing a demo, this is the absolute minimal change (on top of #12) that fixes #11

It is hacky, as it accumulates floating point errors across children. This is likely no issue, but it may become an issue if the camera is a child of a moving object, or if a child of a faraway object is near the camera. I have not tested this yet, but I would like to fix it properly.

The proper fix that I can think of is to do something like `GlobalTransform` (`GlobalGridCell`) that is the accumulated result of all parents' grid cells. Though if we implemented that naively, we'd be ignoring the rotations and scales of the `Transform`s of the parents. This could all get very expensive, so it doesn't seem unreasonable to me to just reject this PR and #11 and add some helper logic to handle a `GlobalGridCell` scheme that doesn't allow for rotation and scaling.

### CODE REVIEW

**Comment by oli-obk** [comment]
The commits all stand on their own. I can pull out [322e9d9](https://github.com/aevyrie/big_space/pull/13/commits/322e9d962d5973bb950b90f5dfd06d0a0ab55e1f), [622f6e0](https://github.com/aevyrie/big_space/pull/13/commits/622f6e079016a36c7298d34ff53f436658d013a5), and [6d2ceb1](https://github.com/aevyrie/big_space/pull/13/commits/6d2ceb1d2b830a1612e7d83a3ce26581f0161694) into their own PRs if you'd like to review them that way.

**Review by aevyrie — COMMENTED** [review]
I've been casually mulling this over in the back of my head for a while now. I think we would want to respect the rotation of the parent, but not the scale. A good test would be tracking an object on the moon, rotating on its axis (grid follows object rotation), rotating about the earth, rotating about the sun. This should make it much easier to keep objects in the same grid from moving relative to each other. Only thing I'm unsure of is if there is enough precision to handle rotating large grids, and where that breaks down.

**Comment by aevyrie** [comment]
I have a working prototype of this in the `reference-frames` branch.

**Comment by aevyrie** [comment]
Closing in favor of #16

**Pull request closed without merging**
